module.exports =
  updateQuestStatus: 'updateQuestStatus'
  setAssign: 'setAssign'
  setQuest: 'setQuest'
  nextQuest: 'nextQuest'
  setBoard: 'setBoard'
  toggleMarkCell: 'toggleMarkCell'
  failQuest: 'failQuest'
  cleanMark: 'cleanMark'
